### ISSUE TITLE
app not opening 

### ISSUE THREAD

**Issue by dhina191295** [subhra74/xdm-experimental-binaries#49]
Recently the app is not opening after clicking on it.uninstalling fixes it and after restart the app does not open again. 

version : 8.0.25

**Comment by dhina191295** [comment]
got this error on first run after re-installing the beta version 8.0.25.

the second run and after than, the app will not open. I could see the icon in the task bar and then closes in few seconds.

![image](https://user-images.githubusercontent.com/77201544/232370641-c0cced4f-8d60-4361-a3ef-0ea09ac7999e.png)

**Comment by dhina191295** [comment]
Found this message when I tried to debug via visual studio

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=xdm-app
  StackTrace:
   at XDM.Wpf.UI.WpfPlatformUIService.ShowMessageBox(Object window, String message)
   at XDM.Core.BrowserMonitoring.IpcHttpMessageProcessor.<Run>b__3_0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
